sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - node
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/basement/basement.git
cache:
  yarn: true
notifications:
  email: false
after_success:
  - git checkout --track origin/master
  - npm run release
branches:
  only:
    - master
